### ISSUE TITLE
images dimensions

### ISSUE THREAD

**Issue by AmaniLouendriz** [AmaniLouendriz/PontsDeConnaisssance#10]
Hello @caseyli !

In the home page, under my 5 courses cards; I have 3 images displayed horizontally; I was wondering why I couldn't set them all to same height even though I specified that each images should be 100% width and height..  

Thank you!

**Comment by caseyli** [comment]
Hey @AmaniLouendriz - so when you specify 100% width and height, usually that means "100% of the containing element". So if you have an image nested within a bunch of `div`s or other elements, each one of those has to have a height set.

For example, if you had something like this...

```
<div class='outer-div'>
  <div class='inner-div'>
    <img class='my-image' src='...' />
  </div>
</div>
```

If you did 100% on the image, that would be 100% of the `inner-div`. But if `inner-div` doesn't have a height set, then it won't know what to do.

So what I would suggest is this. You either explicitly set your height in something like pixels on some of your outer divs, and then set percentages as you go down towards the images OR just set the height and width on the image direclty as pixels.

**Comment by AmaniLouendriz** [comment]
Hello @caseyli , Yess setting my outer div width and height solved the problem ! Thank you :)

**Comment by caseyli** [comment]
@AmaniLouendriz great to hear it worked!
