### ISSUE TITLE
Create a style folder

### ISSUE THREAD

**Issue by caseyli** [AmaniLouendriz/PontsDeConnaisssance#3]
There are a lot of best practices around this, but let's go with the simplest one: putting all your CSS files in a separate folder.

So let's create a "style" folder and put any CSS files in there.

You'll also have to update your style tags in your HTML files to reference the new file location.

**Comment by AmaniLouendriz** [comment]
@caseyli I created the folder; but I also put the picture in it ; because if I didn't do so; it says picture not found. (in the console)

**Comment by caseyli** [comment]
@AmaniLouendriz yeah that makes sense. The other thing you could do is create a another folder called `/images` and put your pictures in there.

The only thing is, wherever you refer to the image, you'll have to update the path. Let me know if you have questions about that.
