### ISSUE TITLE
Organizing cards in the course section part

### ISSUE THREAD

**Issue by AmaniLouendriz** [AmaniLouendriz/PontsDeConnaisssance#9]
Hello @caseyli , @7chris71000 

I hope you're doing fine! Glad to be back again :)) 

So, in the homepage section, I had 5 courses each one containing information about the specific course, well, I liked the idea that 3 cards are on the same line, but in the second line, there's a space between fourth and fifth card, and I want to put the fourth and fifth ones between the cards on the first line; like the fourth between the space of first and second card, and the fifth between the space of the second and third card. I drew my thoughts in the picture attached! I tried doing something but it just makes the five ones in one line. Thank you so much !

Amani
![IMG_20230209_152740_resized_20230209_032909695](https://user-images.githubusercontent.com/90735803/217934373-f066b880-51d3-4328-b829-87d05d6b5b24.jpg)

**Comment by caseyli** [comment]
Hey @AmaniLouendriz,

I'm assuming you're using Flexbox `display: flex` to achieve what you're doing. If so, I would take a look at this: https://css-tricks.com/snippets/css/a-guide-to-flexbox/.

Hint: You're probably dealing with a `justify-content` issue.

**Comment by AmaniLouendriz** [comment]
Yes! That was it. It's fine now !
